# compiler and flags
CXX = g++
CXXFLAGS = -std=c++20 -Wall -MMD -Werror=vla -Isrc/core -Isrc/pieces -Isrc/players -Isrc/ai -Isrc/display -Isrc/patterns -Isrc/utils $(shell sdl2-config --cflags)
LDFLAGS = $(shell sdl2-config --libs) -lSDL2_ttf

# final executable
EXEC = chess

# source directories
SRC_CORE = src/core
SRC_PIECES = src/pieces
SRC_PLAYERS = src/players
SRC_AI = src/ai
SRC_DISPLAY = src/display
SRC_PATTERNS = src/patterns
SRC_UTILS = src/utils

# source files with paths
SOURCES = \
    $(SRC_CORE)/main.cc \
    $(SRC_CORE)/gamecontroller.cc \
    $(SRC_CORE)/board.cc \
    $(SRC_CORE)/scoredposition.cc \
    $(SRC_PATTERNS)/subject.cc \
    $(SRC_DISPLAY)/textdisplay.cc \
    $(SRC_DISPLAY)/graphicsdisplay.cc \
    $(SRC_DISPLAY)/logdisplay.cc \
    $(SRC_UTILS)/window.cc \
    $(SRC_PIECES)/piece.cc \
    $(SRC_PIECES)/rook.cc \
    $(SRC_PIECES)/bishop.cc \
    $(SRC_PIECES)/queen.cc \
    $(SRC_PIECES)/knight.cc \
    $(SRC_PIECES)/pawn.cc \
    $(SRC_PIECES)/king.cc \
    $(SRC_PIECES)/emptypiece.cc \
    $(SRC_PLAYERS)/humanplayer.cc \
    $(SRC_PLAYERS)/computerplayer.cc \
    $(SRC_AI)/ailevel1.cc \
    $(SRC_AI)/ailevel2.cc \
    $(SRC_AI)/ailevel3.cc \
    $(SRC_AI)/ailevel4.cc

# object files
OBJECTS = $(SOURCES:.cc=.o)

# dependencies (auto-generated by -MMD)
DEPENDS = ${OBJECTS:.o=.d}

# default build
all: ${EXEC}

# final link step → link SDL2 libraries
${EXEC}: ${OBJECTS}
	${CXX} ${CXXFLAGS} ${OBJECTS} -o ${EXEC} ${LDFLAGS}

%.o: %.cc
	${CXX} ${CXXFLAGS} -c $< -o $@

run: ${EXEC}
	./${EXEC}

clean:
	rm -f ${OBJECTS} ${EXEC} ${DEPENDS}

-include ${DEPENDS}

.PHONY: all clean run
