# compiler and flags
CXX = g++-14
CXXFLAGS = -std=c++20 -Wall -MMD -Werror=vla

# executables
EXEC = chess
GRAPHICS_EXEC = chess_graphics

# source files
BASE_OBJECTS = \
    main.o \
    gamecontroller.o \
    board.o \
    subject.o \
    textdisplay.o \
    piece.o rook.o bishop.o queen.o knight.o pawn.o king.o emptypiece.o \
    scoredposition.o \
    humanplayer.o computerplayer.o ailevel1.o ailevel2.o ailevel3.o ailevel4.o

GRAPHICS_OBJECTS = graphicsdisplay.o window.o

# dependencies (auto-generated by -MMD)
DEPENDS = ${BASE_OBJECTS:.o=.d} ${GRAPHICS_OBJECTS:.o=.d}

# default build is text-only (does NOT run it)
all: ${EXEC}

# Text-only binary
${EXEC}: ${BASE_OBJECTS}
	${CXX} ${CXXFLAGS} ${BASE_OBJECTS} -o ${EXEC}

# Graphics-enabled binary
${GRAPHICS_EXEC}: ${BASE_OBJECTS} ${GRAPHICS_OBJECTS}
	${CXX} ${CXXFLAGS} -DGRAPHICS ${BASE_OBJECTS} ${GRAPHICS_OBJECTS} -o ${GRAPHICS_EXEC} -lX11

%.o: %.cc
	${CXX} ${CXXFLAGS} -c $< -o $@

run: ${EXEC}
	./${EXEC}

run-graphics: ${GRAPHICS_EXEC}
	./${GRAPHICS_EXEC}

graphics: ${GRAPHICS_EXEC}

clean:
	rm -f ${BASE_OBJECTS} ${GRAPHICS_OBJECTS} ${EXEC} ${GRAPHICS_EXEC} ${DEPENDS}

-include ${DEPENDS}

.PHONY: all clean run run-graphics graphics
