# compiler and flags
CXX = g++-14
CXXFLAGS = -std=c++20 -Wall -MMD -Werror=vla

# final executable
EXEC = chess

# source files
OBJECTS = \
    main.o \
    gamecontroller.o \
    board.o \
    subject.o \
    textdisplay.o \
    graphicsdisplay.o window.o \
    logdisplay.o \
    piece.o rook.o bishop.o queen.o knight.o pawn.o king.o emptypiece.o \
    scoredposition.o \
    humanplayer.o computerplayer.o ailevel1.o ailevel2.o ailevel3.o ailevel4.o

# dependencies (auto-generated by -MMD)
DEPENDS = ${OBJECTS:.o=.d}

# default build
all: ${EXEC}

# final link step → always include graphics code, link X11
${EXEC}: ${OBJECTS}
	${CXX} ${CXXFLAGS} ${OBJECTS} -o ${EXEC} -lX11

%.o: %.cc
	${CXX} ${CXXFLAGS} -c $< -o $@

run: ${EXEC}
	./${EXEC}

clean:
	rm -f ${OBJECTS} ${EXEC} ${DEPENDS}

-include ${DEPENDS}

.PHONY: all clean run
